name: Generate dist when master is updated

on:
  push:
    branch:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - run: npm run build

      - run: |
          git branch dist || true
          git checkout dist
          rm -rf .github/ bin/ node_modules/ src/
          find . -maxdepth 1 -type f | xargs rm -f
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Generate dist/"
          git push origin dist
